module.exports = [
  'Current Firmware (endpoint)',
  'Current Firmware (dongle/base)',
  'Don to answer setting',
  'Endpoint Device Model ID',
  '',
  'Device Serial Number (endpoint)',
  'Device Serial Number (dongle/base)',
  'User modified SideTone Level',
  'Audio codec used',
  'DSP effects enabled by headset',
  'Hardmute/Mute Lock',
  'Headset worn',
  'Battery Level',
  'Device Ready',
  'Radio Link Quality',
  'Error message',
  'Button press info',
  'Connected wireless device change',
  'People count',
  'Local conference count',
]
